[WIP] Democracy guidebook
crustio/crust-wiki pull request #75
Opened 2021-03-25 04:10 UTC by MyronFanQiu

2021-03-31 04:04 UTC, yyd106 commented on website/translated_docs/zh-CN/democracy-guide.md
> +2. 提交议案和复议都会要求抵押一定数值的CRU。预览网上设置的金额大小为**10CRU**。提案一旦进入表决阶段，锁定的金额会自动解锁。但是需要主要的是，当有若干提案候选时，一旦复议某提案，除非该提案进入表决阶段，锁定的CRU是无法解锁的。预览网上，**每7天**会选择得到复议最高的提案进入表决阶段。
注意

2021-03-31 06:24 UTC, yyd106 approved these changes

2021-03-31 06:24 UTC, yyd106 approved these changes

2021-03-31 06:25 UTC, yyd106 commented
Good to go

2021-03-31 06:39 UTC, zikunfan requested changes

2021-03-31 06:39 UTC, zikunfan commented on docs/democracy-guide.md
> +## Process of Democracy module
Add ToC of democracy: proposals&referenda, tech commitee...

2021-03-31 06:39 UTC, zikunfan commented on docs/democracy-guide.md
> +### Main processes
Change this main process to proposal process

2021-03-31 06:39 UTC, zikunfan commented on docs/democracy-guide.md
> +### Main processes
Add section explaination of this process(referenda/proposal process)

2021-04-02 08:12 UTC, zikunfan approved these changes
lgtm

2021-04-02 08:18 UTC, yyd106 commented on docs/democracy-guide.md
> +1. [**Proposals&Referenda**](#1-proposalsreferenda): General democracy module that every one can submit a proposal and vote for the proposal to make Crust Network better.
every one -> everyone

2021-04-02 08:45 UTC, merged