Add Crust Rocky Network Page
crustio/crust-wiki pull request #90
Opened 2021-04-23 06:46 UTC by MyronFanQiu

2021-04-23 06:56 UTC, MyronFanQiu commented on docs/build-crust-sdk.md
> +Please visit [Crust Docs](http://101.132.117.183:8080/) to check all Crust API. You can check the [`Constants`](http://101.132.117.183:8080/substrate/constants) to get all constants stored on chain.
change this ip address

2021-04-23 06:56 UTC, MyronFanQiu commented on docs/build-rocky-guidance.md
> +You can join and check the Crust Rocky Network from our [apps](https://apps.crust.network/?rpc=wss%3A%2F%2Frocky-api.crust.network#/accounts). It's exact same with our Crust Maxwell Preview Network.
change this link

2021-04-23 06:56 UTC, MyronFanQiu commented on docs/build-rocky-guidance.md
> +You can check [Crust Docs](http://101.132.117.183:8080/) website to learn supported api for our chain.
change this ip address

2021-04-23 06:56 UTC, MyronFanQiu commented on website/translated_docs/zh-CN/build-crust-sdk.md
> +Please visit [Crust Docs](http://101.132.117.183:8080/) to check all Crust API. You can check the [`Constants`](http://101.132.117.183:8080/substrate/constants) to get all constants stored on chain.
change this ip address

2021-04-23 06:56 UTC, MyronFanQiu commented on website/translated_docs/zh-CN/build-rocky-guidance.md
> +You can join and check the Crust Rocky Network from our [apps](https://apps.crust.network/?rpc=wss%3A%2F%2Frocky-api.crust.network#/accounts). It's exact same with our Crust Maxwell Preview Network.
change this link

2021-04-23 06:56 UTC, MyronFanQiu commented on website/translated_docs/zh-CN/build-rocky-guidance.md
> +You can check [Crust Docs](http://101.132.117.183:8080/) website to learn supported api for our chain.
change this ip address

2021-04-23 08:23 UTC, zikunfan requested changes

2021-04-23 08:23 UTC, zikunfan commented on docs/build-crust-sdk.md
> +Please visit [Crust Docs](http://101.132.117.183:8080/) to check all Crust API. You can check the [`Constants`](http://101.132.117.183:8080/substrate/constants) to get all constants stored on chain.
After a settled domain

2021-04-26 10:24 UTC, zikunfan approved these changes

2021-04-26 10:27 UTC, zikunfan approved these changes

2021-04-26 10:27 UTC, merged